name: Mend CLI Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: new-fun-project
  DOCKER_REPO_NAME: ${{ github.repository_owner }}
  DOCKER_TAG: dev-${{ github.run_number }}
  MEND_EMAIL: ben.goldberg@mend.io
  MEND_USER_KEY: 2179fbd4279b4017bc4b2ac52afe29cd94a5f7c59306462383ed75e27d3b1fd9
  MEND_URL: https://saas-eu.mend.io

jobs:
  test-app:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: my-amazing-site/package-lock.json
    
    - name: Install dependencies
      run: |
        cd my-amazing-site
        npm ci
    
    - name: Build the React app
      run: |
        cd my-amazing-site
        npm run build
    
    - name: Test the built app
      run: |
        cd my-amazing-site
        
        # Start the preview server in background
        npm run preview &
        SERVER_PID=$!
        sleep 10
        
        # Test basic connectivity
        echo "Testing basic connectivity..."
        curl -f http://localhost:4173 || (echo "App failed to serve" && kill $SERVER_PID && exit 1)
        
        # Test that LLM sections are present in the HTML
        echo "Testing LLM components presence..."
        RESPONSE=$(curl -s http://localhost:4173)
        
        if echo "$RESPONSE" | grep -q "Ask the Cute LLM"; then
          echo "✅ CuteLLM section found"
        else
          echo "❌ CuteLLM section missing"
          kill $SERVER_PID && exit 1
        fi
        
        if echo "$RESPONSE" | grep -q "Text Generation LLM"; then
          echo "✅ TextGenLLM section found"
        else
          echo "❌ TextGenLLM section missing"
          kill $SERVER_PID && exit 1
        fi
        
        if echo "$RESPONSE" | grep -q "Summarization LLM"; then
          echo "✅ SummarizeLLM section found"
        else
          echo "❌ SummarizeLLM section missing"
          kill $SERVER_PID && exit 1
        fi
        
        if echo "$RESPONSE" | grep -q "Sentiment Analysis LLM"; then
          echo "✅ SentimentLLM section found"
        else
          echo "❌ SentimentLLM section missing"
          kill $SERVER_PID && exit 1
        fi
        
        echo "All LLM components found in the built application!"
        
        # Clean up
        kill $SERVER_PID || true

  mend-scan:
    runs-on: ubuntu-latest
    needs: test-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        docker buildx build --platform=linux/amd64 . --file Dockerfile --tag ${{ env.DOCKER_REPO_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }} --load
        docker images

    - name: Install dependencies for dep scan
      run: |
        npm install
        cd my-amazing-site && npm install

    - name: Mend CLI Scan
      run: |
        echo "Downloading Mend CLI"
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        
        echo "Running Mend Dependencies Scan"
        mend dep -u -s "beng_demo_gh//BenG//CSM_V1" -r

        echo "Running Mend Code Scan"
        mend code -s "beng_demo_gh//BenG//CSM_V1" --snippet-size 0

        echo "Running Mend Image Scan"
        mend image ${{ env.DOCKER_REPO_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }} --scope "beng_demo_gh//BenG//CSM_V1" --format sarif --filename results.sarif
    
    - name: Upload Mend Scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif 
