name: Mend CLI Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: new-fun-project
  DOCKER_REPO_NAME: ${{ github.repository_owner }}
  DOCKER_TAG: dev-${{ github.run_number }}
  MEND_EMAIL: ben.goldberg@mend.io
  MEND_USER_KEY: 2179fbd4279b4017bc4b2ac52afe29cd94a5f7c59306462383ed75e27d3b1fd9
  MEND_URL: https://saas-eu.mend.io

jobs:
  mend-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        docker buildx build --platform=linux/amd64 . --file Dockerfile --tag ${{ env.DOCKER_REPO_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }} --load
        docker images

    - name: Install dependencies for dep scan
      run: |
        npm install
        cd my-amazing-site && npm install

    - name: Mend CLI Scan
      run: |
        echo "Downloading Mend CLI"
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        
        echo "Running Mend Dependencies Scan"
        mend dep -u -s "beng_demo_gh//BenG//CSM_V1" -r

        echo "Running Mend Code Scan"
        mend code -s "beng_demo_gh//BenG//CSM_V1" --snippet-size 0

        echo "Running Mend Image Scan"
        mend image ${{ env.DOCKER_REPO_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }} --scope "beng_demo_gh//BenG//CSM_V1" --format sarif --filename results.sarif
    
    - name: Upload Mend Scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif 
